services:
  postgres:
    image: postgres:16
    container_name: postgres-db
    environment:
      # Test credentials
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: urlshortener
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -d urlshortener" ]
      interval: 5s
      timeout: 3s
      retries: 10

  urlshortener-api:
    container_name: urlshortener-api
    build:
      context: .
      dockerfile: UrlShortener.API/Dockerfile
    environment:
      ASPNETCORE_URLS: http://+:8080
      ConnectionStrings__Default: Host=postgres;Port=5432;Database=urlshortener;Username=postgres;Password=postgres
      ASPNETCORE_ENVIRONMENT: Production
    ports:
      - "8080:8080"
    depends_on:
      postgres:
        condition: service_healthy

  urlshortener-mvc:
    container_name: urlshortener-mvc
    build:
      context: .
      dockerfile: UrlShortener.MVC/Dockerfile
    environment:
      ASPNETCORE_URLS: http://+:8081
      ASPNETCORE_ENVIRONMENT: Production
      ConnectionStrings__Default: Host=postgres;Port=5432;Database=urlshortener;Username=postgres;Password=postgres
      Api__BaseUrl: http://urlshortener-api:8080
    ports:
      - "8081:8081"
    depends_on:
      - urlshortener-api

  urlshortener-client:
    container_name: urlshortener-client
    build:
      context: ./UrlShortener.API/client
      dockerfile: Dockerfile
    ports:
      - "5173:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - urlshortener-api

volumes:
  postgres_data:
